### ISSUE TITLE
adjust definition

### ISSUE THREAD

**Issue by aric87** [mse2321/muzak#10]
This function call is only passing 1 argument
https://github.com/mse2321/muzak/blob/master/js/app.js#L66
but the definition is expecting 2 parameters:
https://github.com/mse2321/muzak/blob/master/js/app.js#L82

**Comment by mse2321** [comment]
Hmmm..I see what you are saying. Looks confusing.

**Comment by mse2321** [comment]
Done. I simplified the flow of the functions and separated the findArtist and artistInfo functions.
Made all functions names much more semantic
