### ISSUE TITLE
function to attach event handler

### ISSUE THREAD

**Issue by aric87** [mse2321/muzak#11]
calling this function attaches an event handler. that doesn't really make sense. Also, refactor to use Angular way instead of jQuery. 
https://github.com/mse2321/muzak/blob/master/js/app.js#L74

Also, the way this is written, I can hit enter anytime and it will trigger that function .What you really want is for hitting enter in the input to do that. Change it to a form, and use ng-submit

**Comment by mse2321** [comment]
Done
