### ISSUE TITLE
why results3

### ISSUE THREAD

**Issue by aric87** [mse2321/muzak#13]
https://github.com/mse2321/muzak/blob/master/js/app.js#L103
User variable names that mean something. If it's the results, then use that. the 3 doesn't add any meaning. If you don't want to leave it as results, then make the var name relevant like artist_results or something

**Comment by aric87** [comment]
same note here: https://github.com/mse2321/muzak/blob/master/js/app.js#L194

**Comment by mse2321** [comment]
Done
