### ISSUE TITLE
refactor this

### ISSUE THREAD

**Issue by aric87** [mse2321/muzak#14]
this is hard to reason about. Your adding results data into a scope variable, then adding the scope variable to the object, then pushing into an array. Why not put the results data directly into the object, then push to the array? Is there a reason for the extra step? 
https://github.com/mse2321/muzak/blob/master/js/app.js#L167

also, does the object need to be part of the scope, or can it be a `var` instead?

**Comment by mse2321** [comment]
I have refactored to sent the data right to the object. I guess I was trying to make it more semantic, but after looking at it again, I can see you point.

**Comment by mse2321** [comment]
I'm not sure if I took care of this or not, but can you review and let me know? Also it looks like the highlight is off.

**Comment by mse2321** [comment]
Done
