### ISSUE TITLE
don't use jQuery here

### ISSUE THREAD

**Issue by aric87** [mse2321/muzak#15]
https://github.com/mse2321/muzak/blob/master/js/app.js#L215
you can use window.innerWidth (i believe that's what it is)

**Comment by aric87** [comment]
I see why you're using jQuery here, but there are probably smaller animation libs for Angular. 
https://github.com/mse2321/muzak/blob/master/js/app.js#L214
You could probably add/remove class with ng-class and a scope variable

**Comment by mse2321** [comment]
First part is done.

**Comment by mse2321** [comment]
Done
