### ISSUE TITLE
so, you removed jQuery, but you're still thinking like it's jQuery

### ISSUE THREAD

**Issue by aric87** [mse2321/muzak#19]
https://github.com/mse2321/muzak/blob/master/js/app.js#L128
Instead of finding a DOM element, and adding stuff, you should be thinking Angular. Add a template with an ng-if or something. WIth Angular, you should almost never be trying to grab elements.

**Comment by aric87** [comment]
https://github.com/mse2321/muzak/blob/master/js/app.js#L147
this should be a $scope variable, and it should change on screen size change, 
in the html you should have style="width:{{thingWidth}}" and change that scope var

**Comment by aric87** [comment]
https://github.com/mse2321/muzak/blob/master/js/app.js#L191
this, and the next wo lines, should also be scope vars, and you should update them instead of dealing with the DOM

**Comment by mse2321** [comment]
Ok, I will need to look over the documentation and set that up.

**Comment by mse2321** [comment]
Yeah don't know why I didn't think of that. Anyway, this is all set.
