### ISSUE TITLE
jquery and angular? 

### ISSUE THREAD

**Issue by aric87** [mse2321/muzak#4]
Seems like overkill. Is there a reason you need to load jQuery and jQuery UI? I would try and either refactor the functionality, find an angular lib that does what you need, or write it yourself. Loading all that to sort divs is a waste.
https://github.com/mse2321/muzak/blob/master/index.html#L63

**Comment by mse2321** [comment]
I will review this. I think the Jquery UI is being used.

**Comment by mse2321** [comment]
Done
